[package]
name = "strings"
version = "0.1.0"
authors = ["Michael Held <it@mikeyheld.com>"]
edition = "2018"

[profile.release]
debug = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-instruments = "0.3.4"
